import streamlit as st
import numpy as np
import joblib

# Load trained Lasso regression model
model = joblib.load("diabetes_lasso_model.pkl")

st.title("Diabetes Progression Predictor")

st.warning("""
⚠️ Important Notice: This prediction is generated by a machine learning model trained on a small,
standardized research dataset and should be considered for educational and demonstration purposes only.
""")

# -------- Input Section --------
feature_names = [
    "Age", "Sex", "BMI", "Blood Pressure",
    "Total Cholesterol (TC)", "LDL", "HDL",
    "TCH Ratio", "Triglycerides (LTG)", "Glucose (GLU)"
]

inputs = []
for name in feature_names:
    val = st.number_input(f"{name} (standardized value)", value=0.0, format="%.3f")
    inputs.append(val)

# -------- Prediction --------
if st.button("Predict"):

    arr = np.array([inputs])
    pred = model.predict(arr)[0]

    st.subheader("Prediction Result")

    # 1️⃣ Show numeric prediction
    st.metric("Predicted Diabetes Progression Score", f"{pred:.2f}")

    # 2️⃣ Convert score → severity interpretation
    if pred < 100:
        st.success("🟢 Low Disease Progression")
        severity = 0.3
    elif pred < 200:
        st.warning("🟡 Moderate Disease Progression")
        severity = 0.6
    else:
        st.error("🔴 High Disease Progression")
        severity = 0.9

    # 3️⃣ Visual progress bar
    st.progress(severity)

    # 4️⃣ Short explanation
    st.info("""
Higher scores indicate **greater likelihood of diabetes disease progression**
over time based on clinical measurements.
""")
